[package]
name = "esp32-s31"
version = "0.1.0"
authors = ["Philipp A. <flying-sheep@web.de>"]
edition = "2024"

[[bin]]
name = "esp32-s31"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"
[patch.crates-io]
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf.git" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf.git" }
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf.git" }

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.53", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
embassy-executor = { version = "0.10", features = ["platform-std", "executor-thread"] }
embassy-time = "0.5"
embedded-svc = "0.29.0"
anyhow = "1.0.104"
serde = "1.0.229"
serde_json = "1.0.151"
itertools = "0.15.0"

[build-dependencies]
embuild = "0.33.5"
